import{useEffect,useState}from'react';import axios from'axios';import{isPrivacyMode,MASK_CURRENCY}from'../utils/privacy';import{useScenario}from'../hooks/useScenario';import{SS_OPTS}from'./Simulation';const fmt=n=>isPrivacyMode()?MASK_CURRENCY:new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
// Saving used to always send retirement_age only, and the backend then
// always projected against early SS claiming — so a scenario saved while
// "SS at 67" was selected everywhere else in the app got silently
// recorded as if early claiming had been chosen (external audit
// 2026-09-07, finding #15). ssTiming now comes from the same shared
// scenario module every other page reads/writes (see useScenario), so the
// saved scenario reflects whatever timing is actually currently selected.
export default function SavedScenarios(){const[d,setD]=useState([]),[name,setName]=useState(''),[age,setAge]=useState(60);const{ssTiming}=useScenario();const load=()=>axios.get('/api/saved-scenarios').then(r=>setD(r.data));useEffect(()=>{load()},[]);const save=async()=>{if(!name.trim())return;await axios.post('/api/saved-scenarios',{name,retirement_age:Number(age),ss_timing:ssTiming});setName('');load()};const ssLabel=t=>SS_OPTS.find(o=>o.value===t)?.label||t;return <div><div style={{marginBottom:28}}><h1 className="section-title">Saved Scenarios</h1><p className="section-sub">Keep named retirement tradeoffs side by side as assumptions change.</p></div><div className="card" style={{marginBottom:20,display:'flex',gap:10,alignItems:'center'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Retire at 58"/><input type="number" value={age} onChange={e=>setAge(e.target.value)} style={{width:100}}/><span style={{fontSize:12,color:'var(--text2)'}}>{ssLabel(ssTiming)}</span><button className="btn-primary" onClick={save}>Save scenario</button></div><div className="grid-3">{d.map(x=><div className="card" key={x.id}><div style={{fontWeight:650}}>{x.name}</div><div className="label" style={{marginTop:12}}>Retire at {x.summary.retirement_age} · {ssLabel(x.ss_timing||'early')}</div><div style={{fontSize:22,fontWeight:700,marginTop:5,color:x.summary.on_track?'var(--green)':'var(--amber)'}}>{x.summary.percent_funded}% funded</div><div style={{fontSize:12,color:'var(--text2)',marginTop:8}}>Portfolio {fmt(x.summary.portfolio_at_retirement)}</div></div>)}</div></div>}
